[package]
name = "secretshared"
version = "0.1.0"
edition = "2021"

[dependencies]
redis = "0.23.0"
aes-gcm = "0.10.3"
base64 = "0.21.7"
rand = "0.8.5"
chrono = "0.4.34"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
keyring = "2.0.5"
dirs = "5.0.1"
